# Generated by Django 2.2 on 2019-09-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание товара')),
                ('category', models.CharField(choices=[('other', 'Расзное'), ('processors', 'Процессоры'), ('monitors', 'Мониторы'), ('hdd', 'Жесткие диски'), ('ddr', 'Оперативная память')], default='other', max_length=20, verbose_name='Status')),
                ('count', models.IntegerField(verbose_name='Остаток')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
            ],
        ),
    ]
