# Generated by Django 2.2 on 2019-09-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('other', 'Разное'), ('processors', 'Процессоры'), ('monitors', 'Мониторы'), ('hdd', 'Жесткие диски'), ('ddr', 'Оперативная память')], default='other', max_length=20, verbose_name='Status'),
        ),
    ]
